### ISSUE TITLE
Excluding possibilities based on guesses

### ISSUE THREAD

**Issue by markkvdb** [N-Wouda/wordle#1]
Love that you did this small tools without external dependencies. It's a reminder that simplicity is something to strive for 😄.

I was thinking of the following improvement. If the guess contains a letter that is in hints but the user mentions that this letter is not in the correct place (so not in known), then other words cannot have this letter in the same location.

As an example, say `known = "*****"`, `hints = "OLN", and `guesses = ["PEARS","HUMID","COLON"]` then `wordle.py` gives the following options as of now:

```
BLOWN
FLONG
FLOWN
FONLY
KLONG
KNOLL
LOONY
NYLON
NOBLY
NONYL
NONLY
XYLON
```

However, BLOWN, FLOWN, FONLY, NYLON, NOBLY, NONYL, NONLY, and XYLON can be excluded since an O at place 2 or 4 and N at place 5 is not allowed. That leaves us with just FLONG, KLONG and KNOLL.

**Comment by N-Wouda** [comment]
Heya!

When I try to replicate this I get the following output:

```shell
wordle "*****" "OLN" PEARS HUMID COLON
FLONG
KLONG
KNOLL
```

As far as I can tell that's correctly filtered away any words that contain hints in the wrong places. That's the task of the `hint_positions_ok` function in `Wordle.match()`. Can you check what your `Wordle.match` function looks like?

**Comment by N-Wouda** [comment]
Ahh, what might've happened is that the cases are mixed up. Internally, `classes/Wordle.py` currently uses all lowercase. That's a bit inconsistent with the game, which is all uppercase.

I'll update the argument validation a bit to account for this.

**Comment by N-Wouda** [comment]
Should work OK now, if you pull again!

**Comment by markkvdb** [comment]
Yep, entering `python wordle.py "*****" "PEARS" "HUMID" "COLON" --hints "OLN"` now gives the correct possibilities.

Thanks!
